// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmxnndkhwvvxrvjhgpxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteG5uZGtod3Z2eHJ2amhncHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDE4ODksImV4cCI6MjA2NDg3Nzg4OX0.AMqs7Cth6RSZ-PBqOdHbSXwnTcCKcnPN7yxJQIRlu3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
