// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdhngodqlhdmmiekcwgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkaG5nb2RxbGhkbW1pZWtjd2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzgxNDIsImV4cCI6MjA2NDYxNDE0Mn0.y5eZI2Ofps--Rg9WvpFYcVBpJAlv8PXURmkscDlF8IA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);